### ISSUE TITLE
Running T2WML for development instructions don't work

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/t2wml#142]
Step 3 says to do `pip install t2wml-api -e`

This results in 

```
(t2wml-dev) D22ML-PSZEKELY:t2wml pedroszekely$ pip install t2wml-api -e

Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

-e option requires 1 argument
```

**Comment by zmbq** [comment]
We should update the docs.  t2wml-api is now uploaded as its own package, making the installation simpler.

**Comment by devowit** [comment]
installing it with -e is still an option for development. it's a mistake in the docs, it needs to be `pip install -e t2wml-api` and not `pip install t2wml-api -e.` I'll fix it.

**Comment by saggu** [comment]
The next step is also failing,
```(t2wml_env) amandeep@Amandeeps-MacBook-Pro t2wml % pip install -r server/requirements.txt
Collecting Flask==1.1.2
  Using cached Flask-1.1.2-py2.py3-none-any.whl (94 kB)
Collecting Flask-Cors==3.0.8
  Using cached Flask_Cors-3.0.8-py2.py3-none-any.whl (14 kB)
Collecting Flask-SQLAlchemy==2.4.1
  Downloading Flask_SQLAlchemy-2.4.1-py2.py3-none-any.whl (17 kB)
Collecting Flask-Migrate==2.5.3
  Using cached Flask_Migrate-2.5.3-py2.py3-none-any.whl (13 kB)
ERROR: Could not find a version that satisfies the requirement t2wml-api==0.0.4 (from -r server/requirements.txt (line 5)) (from versions: none)
ERROR: No matching distribution found for t2wml-api==0.0.4 (from -r server/requirements.txt (line 5))
```

**Comment by saggu** [comment]
Ok, I updated the instructions in the`development` branch to the best of my understanding.

Now I can install, but running the frontend is failing,
```
Failed to compile.

/Users/amandeep/Github/t2wml/server/frontend/node_modules/react-bootstrap/esm/index.d.ts
TypeScript error in /Users/amandeep/Github/t2wml/server/frontend/node_modules/react-bootstrap/esm/index.d.ts(2,1):
Declaration or statement expected.  TS1128

    1 | export { default as Accordion } from './Accordion';
  > 2 | export type { AccordionProps } from './Accordion';
      | ^
    3 | export { default as AccordionContext } from './AccordionContext';
    4 | export { default as AccordionCollapse } from './AccordionCollapse';
    5 | export type { AccordionCollapseProps } from './AccordionCollapse';
```

**Comment by kyao** [comment]
I get the same compile error on Ubuntu 18.04 as well.

**Comment by szeke** [comment]
Step 4 fails: Install the remaining requirements from server/requirements.txt pip install -r server/requirements.txt

```
(t2wml-dev) D22ML-PSZEKELY:t2wml-api pedroszekely$ pwd
/Users/pedroszekely/Documents/GitHub/t2wml-api
(t2wml-dev) D22ML-PSZEKELY:t2wml-api pedroszekely$ pip install -r server/requirements.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'server/requirements.txt'
```

**Comment by szeke** [comment]
@devowit @zmbq The instructions are confusing because for each step it is unclear whether it is done in the t2wml or t2wml-api repo.

**Comment by szeke** [comment]
I figured out how to install the requirements, but then the following error happens:
```
(t2wml-dev) D22ML-PSZEKELY:backend pedroszekely$ python application.py
Traceback (most recent call last):
  File "application.py", line 10, in <module>
    from app_config import app
  File "/Users/pedroszekely/Documents/GitHub/t2wml/server/backend/app_config.py", line 69, in <module>
    from models import *
  File "/Users/pedroszekely/Documents/GitHub/t2wml/server/backend/models.py", line 5, in <module>
    from t2wml.api import add_properties_from_file, SpreadsheetFile
  File "/Users/pedroszekely/Documents/GitHub/t2wml-api/t2wml/api.py", line 3, in <module>
    from t2wml.wikification.utility_functions import add_properties_from_file
  File "/Users/pedroszekely/Documents/GitHub/t2wml-api/t2wml/wikification/utility_functions.py", line 4, in <module>
    from t2wml.utils.utilities import VALID_PROPERTY_TYPES
  File "/Users/pedroszekely/Documents/GitHub/t2wml-api/t2wml/utils/utilities.py", line 4, in <module>
    from etk.wikidata.utils import parse_datetime_string
  File "/Users/pedroszekely/opt/anaconda3/lib/python3.7/site-packages/etk/wikidata/utils.py", line 1, in <module>
    from etk.extractors.date_extractor import DateExtractor, DateResolution
  File "/Users/pedroszekely/opt/anaconda3/lib/python3.7/site-packages/etk/extractors/date_extractor.py", line 9, in <module>
    from etk.etk import ETK
  File "/Users/pedroszekely/opt/anaconda3/lib/python3.7/site-packages/etk/etk.py", line 5, in <module>
    from etk.tokenizer import Tokenizer
  File "/Users/pedroszekely/opt/anaconda3/lib/python3.7/site-packages/etk/tokenizer.py", line 8, in <module>
    class Tokenizer(object):
  File "/Users/pedroszekely/opt/anaconda3/lib/python3.7/site-packages/etk/tokenizer.py", line 13, in Tokenizer
    def __init__(self, nlp=spacy.load('en_core_web_sm'), keep_multi_space=True) -> None:
  File "/Users/pedroszekely/opt/anaconda3/lib/python3.7/site-packages/spacy/__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "/Users/pedroszekely/opt/anaconda3/lib/python3.7/site-packages/spacy/util.py", line 169, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
(t2wml-dev) D22ML-PSZEKELY:backend pedroszekely$
```

**Comment by kyao** [comment]
To download that model run:

`python -m spacy download en_core_web_sm`

**Comment by szeke** [comment]
Ok, got it to work to the point where the GUI comes up. The optional ETK step is not really optional. Instructions should be more clear

**Comment by kyao** [comment]
I get this error when running `yarn start`

```
$ yarn start
yarn run v1.22.4
$ react-app-rewired start
ℹ ｢wds｣: Project is running at http://192.168.1.178/
ℹ ｢wds｣: webpack output is served from
ℹ ｢wds｣: Content not from webpack is served from /home/ktyao/dev/dsbox/t2wml/server/frontend/public
ℹ ｢wds｣: 404s will fallback to /
^[[3JStarting the development server...

^[[3JFailed to compile.

./src/data/store.ts
Module not found: Can't resolve '/home/ktyao/dev/dsbox/t2wml/server/frontend/node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/applyDecoratedDescriptor' in\
 '/home/ktyao/dev/dsbox/t2wml/server/frontend/src/data'
^[[3JCompiling...
^[[3JFailed to compile.

./src/data/store.ts
Module not found: Can't resolve '/home/ktyao/dev/dsbox/t2wml/server/frontend/node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/applyDecoratedDescriptor' in\
 '/home/ktyao/dev/dsbox/t2wml/server/frontend/src/data'
```

**Comment by kyao** [comment]
Here is the output of `yarn install`:

```
$ yarn install
yarn install v1.22.4
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsis\
tencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.2: The engine "node" is incompatible with this module. Expected version "^8.16.0 || ^10.6.0 || >=11.0.0". Got "8.10.0"
info fsevents@1.2.12: The platform "linux" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @testing-library/user-event@7.2.1" has unmet peer dependency "@testing-library/dom@>=5".
warning " > bootstrap@4.4.1" has unmet peer dependency "jquery@1.9.1 - 3".
warning " > bootstrap@4.4.1" has unmet peer dependency "popper.js@^1.16.0".
warning " > monaco-editor-webpack-plugin@1.9.0" has unmet peer dependency "webpack@^4.5.0".
warning " > monaco-editor-webpack-plugin@1.9.0" has unmet peer dependency "monaco-editor@0.19.x || 0.20.x".
[4/4] Building fresh packages...


Done in 39.49s.
```

**Comment by saggu** [comment]
@kyao I had the same error. Wait for 30 seconds after `yarn start` and the GUI comes up eventually. I think this might be the reason that the UI fails the first time but works the second time.

@devowit @zmbq something to look into

![image](https://user-images.githubusercontent.com/6811931/89563734-c1094100-d7d0-11ea-9b5f-8f543f22bd1a.png)

**Comment by kyao** [comment]
@saggu For me even after several minutes the GUI fails to come up. That `Failed to compile` message appears.

**Comment by saggu** [comment]
@kyao even after killing the frontend and starting again?

**Comment by kyao** [comment]
Yes

**Comment by zmbq** [comment]
The `development` branch has been reorganized, and the document rewritten. Please try again (it's better to start by cloning again)

**Comment by kyao** [comment]
Installs and runs on Linux

**Comment by kyao** [comment]
Installs and runs on Windows WSL

**Comment by saggu** [comment]
I am closing this issue as we were able to install t2wml locally following instructions in `development` branch
