### ISSUE TITLE
Exception in download

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/t2wml#16]
on file: SL.EMP.TOTL.SP.NE.ZS.xls 

```
[2019-07-08 19:40:38,370] ERROR in app: Exception on /download [POST]
Traceback (most recent call last):
  File "/Users/pedroszekely/Documents/GitHub/t2wml/Code/handler.py", line 175, in generate_download_file
    stat = yaml_parser.get_template()
  File "/Users/pedroszekely/Documents/GitHub/t2wml/Code/YamlParser.py", line 68, in get_template
    self.resolve_template(template)
  File "/Users/pedroszekely/Documents/GitHub/t2wml/Code/YamlParser.py", line 59, in resolve_template
    result = parse_evaluate_and_get_cell(qualifier_value)
  File "/Users/pedroszekely/Documents/GitHub/t2wml/Code/t2wml_parser.py", line 144, in parse_evaluate_and_get_cell
    root = generate_tree(text_to_parse)
  File "/Users/pedroszekely/Documents/GitHub/t2wml/Code/t2wml_parser.py", line 22, in generate_tree
    parse_tree = parser.parse(program)
  File "/Users/pedroszekely/.virtualenvs/t2wml/lib/python3.7/site-packages/lark/lark.py", line 292, in parse
    return self.parser.parse(text)
  File "/Users/pedroszekely/.virtualenvs/t2wml/lib/python3.7/site-packages/lark/parser_frontends.py", line 170, in parse
    return self.parser.parse(text)
  File "/Users/pedroszekely/.virtualenvs/t2wml/lib/python3.7/site-packages/lark/parsers/earley.py", line 307, in parse
    return self.forest_tree_visitor.visit(solutions[0])
  File "/Users/pedroszekely/.virtualenvs/t2wml/lib/python3.7/site-packages/lark/parsers/earley_forest.py", line 281, in visit
    return super(ForestToTreeVisitor, self).visit(root)
  File "/Users/pedroszekely/.virtualenvs/t2wml/lib/python3.7/site-packages/lark/parsers/earley_forest.py", line 204, in visit
    vtn(current)
  File "/Users/pedroszekely/.virtualenvs/t2wml/lib/python3.7/site-packages/lark/parsers/earley_forest.py", line 284, in visit_token_node
    self.output_stack[-1].append(node)
IndexError: deque index out of range
```

**Comment by bhatiadivij** [comment]
It is working fine on my system. Can you please try again after pulling the code from repo?

**Comment by szeke** [comment]
It is working now, please test on other excels. Also, please remove print statements, use a logger instead.

**Comment by bhatiadivij** [comment]
Alright.
