### ISSUE TITLE
Import error when trying to run t2wml-server on development branch

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#173]
Here is the stack dump:
```
~/dev/dsbox/t2wml/backend$ python t2wml-server.py
Traceback (most recent call last):
  File "t2wml-server.py", line 14, in <module>
    from application import app
  File "/home/ktyao/dev/dsbox/t2wml/backend/application.py", line 10, in <module>
    from app_config import app
  File "/home/ktyao/dev/dsbox/t2wml/backend/app_config.py", line 69, in <module>
    from models import *
  File "/home/ktyao/dev/dsbox/t2wml/backend/models.py", line 1, in <module>
    from backend.t2wml_web import wikify
ModuleNotFoundError: No module named 'backend'
```
Changing the first import line of models.py should solve the problem.

**Comment by devowit** [comment]
version 2.2.0
