### ISSUE TITLE
Datamart Integration is broken in branch annoint-merge

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/t2wml#210]
While trying to upload an annotated spreadsheet, I am getting this error,
```
This file is already present in the project's data files
Traceback (most recent call last):
  File "/Users/amandeep/Github/t2wml/backend/application.py", line 212, in upload_data_file
    i_f = ItemsFile.create_from_dataframe(project, combined_item_df)
  File "/Users/amandeep/Github/t2wml/backend/models.py", line 370, in create_from_dataframe
    wf = cls.create_from_filepath(project, filepath)
  File "/Users/amandeep/Github/t2wml/backend/models.py", line 237, in create_from_filepath
    saved_file.add_to_api_proj()
  File "/Users/amandeep/Github/t2wml/backend/models.py", line 374, in add_to_api_proj
    self.project.api_project.add_wikidata_file(self.relative_path)
AttributeError: 'Project' object has no attribute 'add_wikidata_file'
'Project' object has no attribute 'add_wikidata_file'
INFO  [werkzeug] 127.0.0.1 - - [09/Sep/2020 17:33:38] "POST //api/data/12 HTTP/1.1" 200 -`
```

To reproduce, follow these steps,
1. Run these commands in order in a terminal
```
git clone https://github.com/usc-isi-i2/t2wml-annotation

git clone https://github.com/usc-isi-i2/t2wml-api
cd t2wml-api
git checkout development

cd ..
git clone https://github.com/usc-isi-i2/datamart-api
cd datamart-api
git checkout development

python3.6 -m venv datamart_env
source datamart_env/bin/activate
pip install --upgrade pip

pip install -r requirements.txt
pip install -e ../t2wml-annotation
pip install -e ../t2wml-api

cd dev-env
docker-compose up -d # This above step might take a while to complete as it will start and populate the database if  this is the first time running this command. Wait until the database is up and running and available to accept requests

cd ..

python app.py
```

2. Update the datamart api endpoint in t2wml/backend/app_config.py
```
DATAMART_API_ENDPOINT = 'http://localhost:12543'
```
3. Start T2WML from the branch `annoint-merge`

4. Upload this file to a project in T2WML - https://github.com/usc-isi-i2/datamart-api/blob/development/test/test_data/04_worker_incidents.xlsx
5. See the above mentioned error

**Comment by saggu** [comment]
I merged the branch `annotation2` to `annotation-integration`. We should continue working from `annotation-integration`.
