### ISSUE TITLE
CSV, TSV and JSON download options appear to be broken

### ISSUE THREAD

**Issue by g1eb** [usc-isi-i2/t2wml#502]
After updating t2wml backend to the latest version on the `development` branch and the `causx` branch, looks like the download endpoint changed significantly.

I'm getting this error right now:

```
[2021-06-25 23:24:05,387] ERROR in app: Exception on /api/causx/project/download/csv/annotation_example.xlsx_output.csv [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/src/application.py", line 418, in download_results
    return send_file(data, attachment_filename, as_attachment=True, mimetype=mimetype_dict[filetype]), 200
TypeError: send_file() got multiple values for argument 'mimetype'
```

**Comment by g1eb** [comment]
I was trying to debug this myself without any luck so far, @devowit could you take a look please?

**Comment by devowit** [comment]
can we close this as fixed now?
