### ISSUE TITLE
Getting an import error after updating `t2wml-api` to the latest version on the development branch

### ISSUE THREAD

**Issue by g1eb** [usc-isi-i2/t2wml#617]
This is happening on the `causx` branch of the t2wml backend repo after updating t2wml-api to the latest version on `development` branch. See the complete stacktrace below:

```
python t2wml-server.py --public-server --causx
Traceback (most recent call last):
  File "t2wml-server.py", line 19, in <module>
    from causx_application import app
  File "/Users/gleb/t2wml-root/t2wml/backend/causx_application.py", line 22, in <module>
    from t2wml_web import ( get_kg, autocreate_items, set_web_settings,
  File "/Users/gleb/t2wml-root/t2wml/backend/t2wml_web.py", line 9, in <module>
    from t2wml.api import (WikifierService, t2wml_settings, KnowledgeGraph, YamlMapper, AnnotationMapper,
ImportError: cannot import name 'WikifierService' from 't2wml.api' (/Users/gleb/t2wml-root/t2wml-api/t2wml/api.py)
```

**Comment by g1eb** [comment]
From what I understand this was due to a merge issue from the `development` branch to the `causx` branch in t2wml backend repository. The `causx` branch was later removed. I'll switch to use the `development` branch instead and update the demo running on [https://t2wml.isi.edu/](https://t2wml.isi.edu/).
