### ISSUE TITLE
Import Error ItemTable

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#84]
I am getting an ImportError while running with the latest staging branch. @devowit 

```
$ sh run_t2wml_food_prices.sh
Traceback (most recent call last):
  File "../generate.py", line 20, in <module>
    from driver import run_t2wml
  File "/home/kyao/dev/t2wml/driver.py", line 2, in <module>
    from backend_code.item_table import ItemTable
  File "/home/kyao/dev/t2wml/backend_code/item_table.py", line 3, in <module>
    from backend_code.utility_functions import query_wikidata_for_label_and_description
  File "/home/kyao/dev/t2wml/backend_code/utility_functions.py", line 12, in <module>
    from backend_code.wikidata_property import get_property_type as gp
  File "/home/kyao/dev/t2wml/backend_code/wikidata_property.py", line 1, in <module>
    from app_config import db
  File "/home/kyao/dev/t2wml/app_config.py", line 41, in <module>
    from backend_code.models import *
  File "/home/kyao/dev/t2wml/backend_code/models.py", line 7, in <module>
    from backend_code.item_table import ItemTable
ImportError: cannot import name 'ItemTable'
Traceback (most recent call last):
  File "../generate.py", line 20, in <module>
    from driver import run_t2wml
  File "/home/kyao/dev/t2wml/driver.py", line 2, in <module>
    from backend_code.item_table import ItemTable
  File "/home/kyao/dev/t2wml/backend_code/item_table.py", line 3, in <module>
    from backend_code.utility_functions import query_wikidata_for_label_and_description
  File "/home/kyao/dev/t2wml/backend_code/utility_functions.py", line 12, in <module>
    from backend_code.wikidata_property import get_property_type as gp
  File "/home/kyao/dev/t2wml/backend_code/wikidata_property.py", line 1, in <module>
    from app_config import db
  File "/home/kyao/dev/t2wml/app_config.py", line 41, in <module>
    from backend_code.models import *
  File "/home/kyao/dev/t2wml/backend_code/models.py", line 7, in <module>
    from backend_code.item_table import ItemTable
ImportError: cannot import name 'ItemTable'
```

**Comment by devowit** [comment]
I have pushed a fix to this error to staging branch.
